filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /root/pcap/pcap.csv # path to the CSV file
  exclude_lines: ['^\"\"']          # header line to exclude
  index: sales
  processors:
    - decode_csv_fields:
        fields: 
          message: decoded.csv 
        separator: ","
    - extract_array:
        field: decoded.csv
        mappings:
          date: 0
          ip.src: 1
          ip.dst: 2
          udp.dstport: 3
          ip.len: 4
    

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["search-networkmonitor-h2s7x4tpkxqaydrghfxl6emn2e.us-east-1.es.amazonaws.com:443"]
  protocol: "https"
  index: "packet-filebeat-%{+yyyy.MM.dd}"
  setup.template.enabled: true
  setup.template.name: "packet-filebeat"
  setup.template.pattern: "packet-filebeat-*"
setup.ilm.enabled: false
setup.template.enabled: false
